const DEFAULT_ERROR_COLOR = '#ff5733';
const DEFAULT_SELECTED_BACKG_COLOR = '#DCE9FF';
const DEFAULT_UN_SELECTED_BACKG_COLOR = '#FFFFFF';


const COMPONENT_TYPE_INPUT = 'input';
const COMPONENT_TYPE_SELECT = 'select';


export {
    DEFAULT_ERROR_COLOR,
    DEFAULT_SELECTED_BACKG_COLOR,
    COMPONENT_TYPE_INPUT,
    COMPONENT_TYPE_SELECT,
    DEFAULT_UN_SELECTED_BACKG_COLOR
}